version: 0.0
os: linux
files:
  - source: /
    destination: /var/deploy/piper-generic-handler
hooks:
  BeforeInstall:
    - location: .deploy/before_install.sh
      timeout: 300
      runas: ubuntu
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: .deploy/start_server.sh
#      timeout: 300
#      runas: ubuntu
#  ApplicationStop:
#    - location: .deploy/stop_server.sh
#      timeout: 300
#      runas: root
